### ISSUE TITLE
Tài liệu tham khảo

### ISSUE THREAD

**Issue by khoantv** [bangoc123/learn-machine-learning-in-two-months#3]
Có một trang về Machine Learning cũng rất hay, mọi người có thể tham khảo về lộ trình học, các kiến thức cần thiết và các trang web, blog khác.

https://machinelearningcoban.com/2016/12/26/introduce/

**Comment by tiger-1974** [comment]
Link rất tuyệt, tks Ngọc

**Comment by skulldice003** [comment]
Hay quá  thanks anh

Vào 15:01, T.6, 24 Th8, 2018 tiger-1974 <notifications@github.com> đã viết:
