### ISSUE TITLE
Is Stanford CS229 a good course to learn about ML?

### ISSUE THREAD

**Issue by DuyAnhTran95** [bangoc123/learn-machine-learning-in-two-months#4]
I've found this course by Prof. Andrew Ng
[https://see.stanford.edu/Course/CS229](url)
I'm wondering is this a good course to study Machine Learning?

**Comment by tiger-1974** [comment]
Look like very great resource , thanks DuyAnhTran95 for sharing

**Comment by bangoc123** [comment]
@DuyAnhTran95 yes it is good course for ML.

If you want to learn more about Deep Learning, you should follow two courses below:

[Natural Language Processing with Deep Learning - Stanford](http://web.stanford.edu/class/cs224n/)

[Convolutional Neural Networks for Visual Recognition - Stanford](http://cs231n.stanford.edu/)
