### ISSUE TITLE
Review Bubble Sort Output Result

### ISSUE THREAD

**Issue by khoantv** [bangoc123/learn-machine-learning-in-two-months#6]
Bubble Sort output code, maybe has a mistake. The result must be: [89, 20, 16, 10, 6]

![image](https://user-images.githubusercontent.com/11270138/46710420-e62ed600-cc71-11e8-91df-79c5589946b6.png)

**Comment by bangoc123** [comment]
@truongkhoan92 yes I will check the code again.
